### ISSUE TITLE
Wrong number of splits

### ISSUE THREAD

**Issue by LKAMinco** [Jrome90/Fast-Loop#10]
Idk if this is and feature, but i think that longer markers should mark size by 5, now there is an offset by 1, what lead to wrong numbering and cunfusion.
![image](https://github.com/Jrome90/Fast-Loop/assets/70859762/9d83c6f6-f344-4287-9706-313a05d3c28b)

**Comment by Jrome90** [comment]
I can see how it causes confusion. It's not immediately clear that the both the location of the ticks, and the mirrored loop on the right side is correct.
But is indeed the case. The case in which the mirrored loop doesn't line up with the nearest tick is a consequence of the edge's length not being evenly divisible by the distance between each tick mark.

Here in this example below the edge's length is 2.5m and the distance between tick marks is 0.012m
2.5 is not evenly divisible by 0.012.
![image](https://github.com/Jrome90/Fast-Loop/assets/11284891/ed94f95b-8d49-4911-aa16-8cec245f808f)

Here the edge's length is 2.5m and the distance between tick marks is 0.01m
2.5 is evenly divisible by 0.01, so in this case the loops and the ticks do line up.
![image](https://github.com/Jrome90/Fast-Loop/assets/11284891/dd8e6cb6-1f10-444a-8185-7d6c7b961eb7)

**Comment by LKAMinco** [comment]
Ohh yeah i see, in that case it woul be more intuitive if user use distance snap that longer markers would marks multiplication of 5 or maybe just in case where u have set distance to dividable number.

**Comment by Jrome90** [comment]
> Ohh yeah i see, in that case it woul be more intuitive if user use distance snap that longer markers would marks multiplication of 5 or maybe just in case where u have set distance to dividable number.

To clarify, you are wanting the major ticks to be every 5 ticks instead of 4?
I have plans to make the major ticks every nth tick, where the user can set the value of n to whatever they wanted,

**Comment by LKAMinco** [comment]
Yep, in that case your solution is even better.

**Comment by Jrome90** [comment]
> I have plans to make the major ticks every nth tick, where the user can set the value of n to whatever they wanted,

Pushed an update to add this.

**Comment by LKAMinco** [comment]
Major tick multiplier reset each call of operator. Would be nice if it can be set once and saved. All the settings could be shared among files or at least in current blendfile.

**Comment by Jrome90** [comment]
> Major tick multiplier reset each call of operator. Would be nice if it can be set once and saved. All the settings could be shared among files or at least in current blendfile.

Sorry, I forgot to add it as an exception when resetting the operator's properties.
Unfortunately, I don't have a way of saving the state of the operator's props to the blendfile or the addon's settings.

Anyways, I pushed a change that should address the reset.

**Comment by LKAMinco** [comment]
I know that properties can be registered in the scene, which can save then states along blendfile

**Comment by Jrome90** [comment]
> I know that properties can be registered in the scene, which can save then states along blendfile

This is true.

I just pushed a change to save the property group stored in the scene.
It should now allow most of the snap options to be saved with the blendfile.
