### ISSUE TITLE
Error while "Use Selected Edges"

### ISSUE THREAD

**Issue by LKAMinco** [Jrome90/Fast-Loop#11]
While i am using selected edges method, and i am trying to increase loop count, the addon will crash.

![image](https://github.com/Jrome90/Fast-Loop/assets/70859762/ee0d6df3-272d-4ca6-bb72-ef800dfc7c60)

**Comment by Jrome90** [comment]
I'm not getting able to get it to error. 
But I did add a check that hopefully prevents the error from occurring.
Most recent version: 2.0.2

**Comment by LKAMinco** [comment]
![image](https://github.com/Jrome90/Fast-Loop/assets/70859762/507790d7-57eb-481b-8701-dde4f3dabbb0)
This is test scenario
