### ISSUE TITLE
Max count of loop

### ISSUE THREAD

**Issue by LKAMinco** [Jrome90/Fast-Loop#12]
Is it possible to increace max count of loops to 128 or 256, since blender supports 500 the 256 should not be a problem

**Comment by Jrome90** [comment]
It's certainly possible. But right now, there is no way to easily set it to 500 loops.
You can press and hold <kbd>=</kbd> to increase to loop count to a max arbitrary value of 100. But there is no visual way to know how many loops you have it set to.

**Comment by Jrome90** [comment]
Pushed a change that increases the max loop count to 500, and displays how many loops are to be inserted.
