### ISSUE TITLE
Error message when activating addon

### ISSUE THREAD

**Issue by retmia** [Jrome90/Fast-Loop#13]
HI ! Thanks for your work !
Being able to cut with edge flow in one click is a biiiiig lack of Blender. I use it a lot to box model organic shapes and characters in Maya.
Unfortunately, I can't make your addon work on my computer (macbook), I have the following error message :

![Capture d’écran 2024-03-25 à 20 50 01](https://github.com/Jrome90/Fast-Loop/assets/13124495/5c9fa6fa-a4f3-4757-99f1-4983acb4cb50)

I hope you can fix it ! And I'd dream your addon be added to blender by default with the edge-flow addon !

Thanks again !
Regards,
Romain

**Comment by Jrome90** [comment]
Please try renaming the addon folder to Fast Loop after unzipping.

**Comment by retmia** [comment]
Thanks ! It works !
