### ISSUE TITLE
bforartists addon crash 

### ISSUE THREAD

**Issue by CMC-3D** [Jrome90/Fast-Loop#14]
[bforartists.crash.txt](https://github.com/Jrome90/Fast-Loop/files/14798205/bforartists.crash.txt)

Crashes when selecting it in toolbar, happens in any file/new. Bforartists version 4.0.2
lmk if you need more logs.

*edge flow addon is installed

**Comment by Jrome90** [comment]
Thanks. I will look into it.

**Comment by Jrome90** [comment]
I was unable to find a download for Bforartists 4.0.2.
However I did download Bforartists 4 - Version 4.1.0, and had no issues.

**Comment by CMC-3D** [comment]
> I was unable to find a download for Bforartists 4.0.2. However I did download Bforartists 4 - Version 4.1.0, and had no issues.

Oh, I need to update it. Might be fixed.

**Comment by CMC-3D** [comment]
Nope. It seems to be a problem with a shortcut I changed, which is ''KeyError: 'bpy_prop_collection[key]: key "ed.undo" not found''' as the log mentions. Could the addon somehow skip that?

**Comment by Jrome90** [comment]
sure I can make it skip the check, but How do you perform an undo?
Please share your custom keymap so I can address this. 
Thanks.

**Comment by CMC-3D** [comment]
oh, does ''ed.undo_history'' work? As I only use that. Key is Button5 Mouse. 

hmmm sorry idk anything about coding, but are you changing the default keymap that the addon uses or will it automatically detect?

**Comment by Jrome90** [comment]
I'm not sure that will work as an alternative. But I'll test it, and get back to you.

**Comment by Jrome90** [comment]
> hmmm sorry idk anything about coding, but are you changing the default keymap that the addon uses or will it automatically detect?

If a keymap for ed.undo is not found it will check if there is a keymap set for undo history. If it finds one for undo_history it will fall back to that instead.

Let me know if it works.

**Comment by CMC-3D** [comment]
It works now. Thanks a lot man, I am also amazed at the amount of functions it has compared to the previous FL.

**Comment by Jrome90** [comment]
> It works now. Thanks a lot man, 
You're welcome. I'm glad it works.

> I am also amazed at the amount of functions it has compared to the previous FL.
The original one was lacking some features that are a must have, namely snapping, tools for precision, and UV preservation among others.
