### ISSUE TITLE
Error trying to activate 

### ISSUE THREAD

**Issue by brunoosti** [Jrome90/Fast-Loop#15]
Getting this error (blender 4.0): 

![image](https://github.com/Jrome90/Fast-Loop/assets/70181464/52470a4a-3663-4519-b1b7-a172e61cf2fa)

**Comment by Jrome90** [comment]
You have to rename the addon folder to Fast Loop. If you don't blender will error when enabling.
This happens to a lot of people. If only I could control the zip file name GitHub uses.
Sorry.

**Comment by brunoosti** [comment]
Oh! It worked : ) Thank you! No need to be sorry. My bad, i simply didn't read that going fast through the readme. 
Thank your for the addon!

**Comment by Jrome90** [comment]
Recommended to use Blender 4.2+ with the extension instead of the legacy addon:
https://github.com/Jrome90/Fast-Loop/tree/Blender-4.2-Extension
