### ISSUE TITLE
Change the Number of Snaps?

### ISSUE THREAD

**Issue by triplet0** [Jrome90/Fast-Loop#16]
Are we able to change the number of snap points when they are enabled? Currently I only see 1-2 snap points, I've also noticed sometimes it doesn't snap to the points even if they are showing.

**Comment by Jrome90** [comment]
> Are we able to change the number of snap points when they are enabled? 

Assuming you are using Blender 4.0 and above:
While the tool is active, under "Active Tool", there is the "Snap Divisions" slider. You can change the number of points there. The slider has a soft limit of 10 but you can use up to 100 by typing in a different value.
  
If "Use Distance" is enabled (It is by default) then the number of segments displayed is based upon the "Distance" value and the number of snap divisions.
For example, if you have a default cube, the length of any edge is 2 meters. If the "Distance" value is 0.1m, and "Snap Divisions" is set to 1, then you will only see one snap point. But if you were set the number of snap divisions to let's, say 5, there will be 5 points spaced by 0.1m. With 10 snap divisions there will be 10. And 20, there will be a max of 20 - 1, or simply 19. (You can only fit 19 points spaced 0.1m apart between the edge's vertices (The edge length is 2m)).

You may also notice that when you move the mouse pass the edge's center point, the points move to the side with the nearest vertex to the mouse. The values displayed at the major ticks will also change to their newly calculated values from that vertex.
If you don't want the points to move at all, you can lock/unlock the snap points by pressing <kbd>x</kbd>.

Oh, I forgot to mention that you can calculate the snap points starting at the center by toggling the "Center Button" at the bottom.
Also, with "Auto" enabled it will override the "Snap Divisions" value and calculate how many to use along the edge.

>I've also noticed sometimes it doesn't snap to the points even if they are showing.

What version of blender are you using?
 Does it only happen with certain edges? Perhaps there is an edge case that I am not aware of that causes it to break.
If so, could you please send me a blend file that has only those edges where it does happen?

**Comment by triplet0** [comment]
Thank you for the explanation, im still new to blender and didn't have the active tool window up. You could say I didn't even remember about it till you mentioned it. Everything is working as expected. I cant get it to replicate the not snapping to points at home, since that was happening on my work PC. I will try to replicate it tomorrow.

**Comment by Jrome90** [comment]
Closing with the assumption there are no issues.
