### ISSUE TITLE
Earlier shortcut of shift click.

### ISSUE THREAD

**Issue by frankenstein07** [Jrome90/Fast-Loop#18]
https://www.youtube.com/watch?v=Zi1qesVy5rE&t=238s

I had been going through this tutorial for that specific use case. Keeping the curvature of the mesh while inserting the loop. He is using shift click method to do it. But with this version, shift click is not working and it is destroying the geometry.

The workflow changed? Or curvature is not supported anymore?

Thanks in advance. Kindly help. Stuck in a project!

**Comment by Jrome90** [comment]
It's hard to say what the problem is.  I just tested it with blender 4.1 and it seems to work fine.
The author of the set flow addon released a newer version.  Maybe there were some changes that give different results compared to the one used in that video you shared.

What is shift click doing? How is it destroying the geometry?

**Comment by frankenstein07** [comment]
Hi.

Lets say I subdivided a geometry. When I add one edge loop in between, it destroys the already established curvature. This has been a limitation of blender's loop insert for a long time.
In max, there is swift loop tool which places the loop where it should ideally cut after subdivision so that curvature is maintained. This is especially important in automotive surfacing which is my case.

In the video link i shared, when he is adding the loop on the cylinder, its taking into account the curvature. 

I was looking for that feature.

Thanks in advance.

**Comment by Jrome90** [comment]
At this point in the video: https://youtu.be/Zi1qesVy5rE?t=232?

**Comment by frankenstein07** [comment]
Yes.

**Comment by Jrome90** [comment]
What version of blender are you using?

**Comment by frankenstein07** [comment]
4.2.

It works in other versions?

**Comment by Jrome90** [comment]
I haven't tested it in 4.2. I was just about to, but the VS Code extension for blender development just erased my entire local repo.
Yes, It works fine  for me in 4.1

**Comment by frankenstein07** [comment]
Oh. Thanks. I will check and revert.

Thanks for the feature mate.!

**Comment by frankenstein07** [comment]
https://github.com/user-attachments/assets/6bbdc6a0-93a2-479c-b662-bf30082b39d8

Unfortunately no. Its still showing weird results in 4.1.

I am holding shift while inserting the loop with left click.

**Comment by Jrome90** [comment]
Unfortunately, I don't think this has to do with my addon. The only thing my addon does is pass the selected edges to the set flow operator to run.

Maybe the latest version of set flow is the issue?

I will continue to investigate though.

**Comment by frankenstein07** [comment]
I see. Which version of edge flow addon should I use? In the edge flow github page, there is only two versions. 2023 glow up release and 2.8 release. Should I check with 2.8 one? Are you using the same since it works for you?

**Comment by frankenstein07** [comment]
Tried 2.8 release of edge flow. Same result!

Some conflict I guess.

**Comment by Jrome90** [comment]
I only tried adding edge loops to the sides like you did at 13 seconds in.
I did not add additional support loops before.

One I get 4.2 up and running I will try to replicate what you did.

**Comment by frankenstein07** [comment]
Okay Thanks. I tried with older version of edge flow as well.
 
 Without support loops, it is maintaining curvature. But its same result as the video I shared with support loops. Weird. I will have to experiment and figure out a work around.

**Comment by Jrome90** [comment]
![setflow](https://github.com/user-attachments/assets/be4f1a3f-ee92-4fcd-a286-64a82742a992)

I don't seem to have any issues using 4.2.

**Comment by Jrome90** [comment]
I am using edge flow ver 0.8
[EdgeFlow0.8.zip](https://github.com/user-attachments/files/16467004/EdgeFlow0.8.zip)

**Comment by frankenstein07** [comment]
Oh. Maybe that's why. I will try this version of edge flow. 
Thanks again.

**Comment by Jrome90** [comment]
It appears to be the same version on his github. 
What are your set flow options for fast loop set to? Should be this if it's not:
![image](https://github.com/user-attachments/assets/80706a46-2d29-4f63-9853-81960533b0ba)

**Comment by Jrome90** [comment]
Oh I'm sorry. The issue is you have edges selected before clicking shift+left mouse button
You mustn't have any edges already selected, or the set flow addon will use those too.

**Comment by frankenstein07** [comment]
Oh my god.! Such a simple thing! So used to native loop tool workflow. Selection is not an issue right.!

I deselected like you said and voila!

**Comment by frankenstein07** [comment]
Closing the thread. Hopefully someone will find this thread useful!
