### ISSUE TITLE
How to keep mesh curvatures when adding loop cuts?

### ISSUE THREAD

**Issue by FDSACXG** [Jrome90/Fast-Loop#20]
I learned about this plugin from a video a few years ago, which included a feature to insert loop edges while holding SHIFT to maintain curvature. However, I can’t find this function in the current version; I’m using Blender 4.2.

**Comment by Jrome90** [comment]
The feature is still there. Please make sure you have at the min, version 0.8 of edge flow installed.  https://github.com/user-attachments/files/16467004/EdgeFlow0.8.zip

**Comment by FDSACXG** [comment]
> The feature is still there. Please make sure you have at the min, version 0.8 of edge flow installed. https://github.com/user-attachments/files/16467004/EdgeFlow0.8.zip

Thanks. I already download 0.9 version of Edge Flow, but it still doesn't work. Does the shortcut is changed to anyother button? I checked the keymaps setting, but I didn't find any shotcut for this feature.

**Comment by NicCrimson** [comment]
> Thanks. I already download 0.9 version of Edge Flow, but it still doesn't work. Does the shortcut is changed to anyother button? I checked the keymaps setting, but I didn't find any shotcut for this feature.

Same I can't seem to get this feature to work.

**Comment by Jrome90** [comment]
No, I haven't changed it from holding shift.
I'll look into it with version 0.9.
Thanks

**Comment by Jrome90** [comment]
I updated the blender 4.2 branch to work with EdgeFlow 0.9 extension. 
https://github.com/Jrome90/Fast-Loop/tree/Blender-4.2-Extension

**Comment by FDSACXG** [comment]
> I updated the blender 4.2 branch to work with EdgeFlow 0.9 extension. https://github.com/Jrome90/Fast-Loop/tree/Blender-4.2-Extension
It works now.
Thanks
