### ISSUE TITLE
Addon Breaks with versions higher than EdgeFlow 0.8

### ISSUE THREAD

**Issue by NicCrimson** [Jrome90/Fast-Loop#21]
Seems to only work with this version and not the latest release of EdgeFlow which would be 0.9

**Comment by Jrome90** [comment]
I will see what needs to be done to get it to work properly. 
Thanks

**Comment by Jrome90** [comment]
I updated the blender 4.2 branch to work with EdgeFlow 0.9 extension.
https://github.com/Jrome90/Fast-Loop/tree/Blender-4.2-Extension

**Comment by nurb2kea** [comment]
Hi,
again ... where to find the  latest release of EdgeFlow which would be 0.9 ?

I have no idea where and why it's hidden. I asked the days about the fast loop link:
https://github.com/Jrome90/Fast-Loop/tree/Blender-4.2-Extension

so why is it hidden?

Thanks in advance :-)

**Comment by Jrome90** [comment]
You can edge flow 0.9 here:
https://github.com/BenjaminSauder/EdgeFlow

**Comment by nurb2kea** [comment]
Yepp but it's the 0.8 version and not the 0.9.
This link is in your Fast-Loop discription, but I'm looking for the above mentioned 0.9 version.
Or did I understand something wrong?

**Comment by Jrome90** [comment]
> Yepp but it's the 0.8 version and not the 0.9. This link is in your Fast-Loop discription, but I'm looking for the above mentioned 0.9 version. Or did I understand something wrong?

Oh I see.
The master branch version is 0.8 in the `__init__.py` file.
And 0.9 in the `blender_manifest.toml` file. (Used with extensions)

The master branch is the one you want.

**Comment by nurb2kea** [comment]
I stay with the before version and latest fast-loop, because with blender 4.4 macOS silicon, EdgeFlow 0.8 with the .toml file is having only errors. (master)
Anyways, thanks for the help !

**Comment by Jrome90** [comment]
> I stay with the before version and latest fast-loop, because with blender 4.4 macOS silicon, EdgeFlow 0.8 with the .toml file is having only errors. (master) Anyways, thanks for the help !

What version of Edge Flow are you using?
Is it incompatible with the latest fast loop version?

**Comment by nurb2kea** [comment]
I'm using the 0.8 version without the .toml file. (addon, not extension)
https://github.com/BenjaminSauder/EdgeFlow/releases/tag/0.8
with
Fast-loop 2.1.0 with the .toml file (as extension)

-----------------------------------------------
explanation:
-----------------------------------------------
The master version of edge flow is making problems 
👍 https://github.com/BenjaminSauder/EdgeFlow/archive/refs/heads/master.zip

Now I tried to install this: https://extensions.blender.org/add-ons/edgeflow/ 
also with no luck for blender 4.4.

But I informed the edge flow dev. about it.

I'm on lates MacOS silicon and blender 4.4 silicon

**Comment by Jrome90** [comment]
> I'm using the 0.8 version without the .toml file. (addon, not extension) https://github.com/BenjaminSauder/EdgeFlow/releases/tag/0.8 with Fast-loop 2.1.0 with the .toml file (as extension)

Are you sure you are using Fast Loop 2.1.0?
You should have the latest (2.1.2) if you recently updated after the fix to address the slow down discussed here:
https://github.com/Jrome90/Fast-Loop/issues/23#issuecomment-2497223245

**Comment by nurb2kea** [comment]
Yes,
you're right & me too... :-)
Maybe this should be changed.
![Screenshot 2024-11-28 at 12 08 12 am](https://github.com/user-attachments/assets/734dbcd6-e8f8-4698-bf40-f6b357262d5f)

**Comment by Jrome90** [comment]
I'm sorry for the confusion. I didn't bother changing it since it's commented out.
I'll remove the commented out bits.

**Comment by nurb2kea** [comment]
No need to be sorry.
I always check the init file for versions.
The extensions .toml file is kinda dangerous in my eyes. Typing something wrong in it ends up in blender crash at start...
Like blender_version_max...if you change it to a higher build number and the addon code is the same, blender crashes...
Had this today with another addon that wouldn't install because of the blender_version_max = "4.3.0". I changed it to 4.4.0 and blender crashed all the time. Even while I'm using one of two 4.4 versions.

**Comment by nurb2kea** [comment]
That's the answer: https://github.com/BenjaminSauder/EdgeFlow/issues/32#issuecomment-2506001032

soo, looks like the extension & master version isn't updated to work soon...
