### ISSUE TITLE
Loop Cut Edge Flow doesn't work properly.

### ISSUE THREAD

**Issue by NicCrimson** [Jrome90/Fast-Loop#22]
It only work while in Edge Mode. It also doesn't work if the mesh faces/verts/edges are selected. Which it does by default. It collapses the entire mesh if you don't. You have to deselect them before it works.

https://github.com/user-attachments/assets/d1ab20f5-e8a7-4b23-b410-1c40e2e6f3eb

**Comment by Jrome90** [comment]
This is a limitation of the Edge flow addon. It works on selected edges.
