### ISSUE TITLE
Fastloop is not showing the green loop anywhere, help

### ISSUE THREAD

**Issue by Agroithien** [Jrome90/Fast-Loop#5]
It was working before but not now, It happened during the project.

I'm uploading to my g-Drive with a video and the .blend file, 
It's not working even if I do append on a new project nor export and importing fbx...
I'm using Blender 3.4.1 on PopOS! 
The fast loop is working when I'm creating a new blender file or starting a new project, but after some time it doesn't show the green line, 
`https://drive.google.com/drive/folders/17lfmior-Q5N8s5LtcAL5pUT_l75xxkoN?usp=sharing`

**Comment by Jrome90** [comment]
Apologies for not seeing this sooner. Are you able to reproduce the issue? If so can you please share the steps.
Thanks

**Comment by Agroithien** [comment]
I'm sorry I couldn't recreate the issue so maybe everything is fine...( I tried of weeks ) but no luck...
