### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by LKAMinco** [Jrome90/Fast-Loop#8]
Is it possible to add snap move by 1cm/1mm

**Comment by Jrome90** [comment]
> Is it possible to add snap move by 1cm/1mm

I'm sorry, I don't understand what you are asking for.

**Comment by LKAMinco** [comment]
I mean that sliding to sides will be snapped to round numbers eg 0.01cm, 0.02, because now to make loopcut at exact number is lil hard if u want some precision.

**Comment by Jrome90** [comment]
> I mean that sliding to sides will be snapped to round numbers eg 0.01cm, 0.02, because now to make loopcut at exact number is lil hard if u want some precision.

In Fast Loop 2.0 you can change the distance along the edge that snap points are at, using the use distance check box and entering a value into the input box below it.
![image](https://github.com/Jrome90/Fast-Loop/assets/11284891/4d4bd88f-2aaa-4b42-85ee-9c12464360ee)

**Comment by LKAMinco** [comment]
Yes, but that works just for creating loop, not sliding (alt key).

**Comment by Jrome90** [comment]
> Yes, but that works just for creating loop, not sliding (alt key).

Oh, right.
I'm not sure how I would go about making something like this work. I could probably add numeric input and have use that to set a specific distance. 

However, this wouldn't work well with edge slide being invoked by pressing <kbd>alt</kbd>. The reason being you'd have to hold down alt to keep edge slide active while typing in a value. That would be awkward to do.
