### ISSUE TITLE
Vertices on single edge

### ISSUE THREAD

**Issue by LKAMinco** [Jrome90/Fast-Loop#9]
Is it possible to add option, to loopcut on edges that doesn't contain faces (single edges) ?

**Comment by Jrome90** [comment]
> Is it possible to add option, to loopcut on edges that doesn't contain faces (single edges) ?

Unfortunately, I don't think I will be able to add this feature. 
Right now, I rely upon doing a raycast. 
And a raycast requires geometry to be hit to get a resulting position.

Things get a bit more complicated when you want to detect loose edges, and that's a beyond my knowledge.
